#!/usr/bin/env bash

set -e

DB="valgrind-tests-$RANDOM"

valgrind --vgdb=full --tool=memcheck --leak-check=full ./luaval -n -d "$DB"
valgrind --vgdb=full --tool=memcheck --leak-check=full ./luaval -n -d "$DB" -e "a = 1"
valgrind --vgdb=full --tool=memcheck --leak-check=full ./luaval -n -d "$DB" -e "a = 2"
valgrind --vgdb=full --tool=memcheck --leak-check=full ./luaval -n -d "$DB" -c 1 -e "return a"
